---

  # Main playbook for environment configuration

  # Test playbook with hello world
  # - import_playbook: helloworld.yml
  #   tags:
  #     - test

  # Main playbook for Cirras application
  - import_playbook: app.yml
    tags:
      - app

  # Main playbook for Cirras proxy
  - import_playbook: client.yml
    tags:
      - client
